name: Bug Report
description: The jsx parsing is not as expected
labels: jsx-bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: input
    id: playground-url
    attributes:
      label: Input code
      render: typescript
  - type: textarea
    id: expected
    attributes:
      label: Input code
      render: typescript
